replicaCount: 1

resources:
  limits: { cpu: "1", memory: 1Gi }
  requests: { cpu: 400m, memory: 512Mi }

ingress:
  enabled: true
  host: ""
  staticIP: "api-gateway-ip"
  className: "gce"

config:
  INDEX_INTERVAL: "30000"
