# infrastructure/services/api-gateway/templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lib.fullname" . }}
  labels: {{ include "lib.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIP }}
    kubernetes.io/ingress.allow-http: "true"
spec:
  defaultBackend:
    service:
      name: {{ include "lib.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}
