apiVersion: v1
kind: Service
metadata:
  name: {{ include "lib.fullname" . }}
  labels: {{ include "lib.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector: {{ include "lib.selector" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
