replicaCount: 1

image:
  tag: "{{ .Values.global.gitSha }}"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  host: ""
  staticIP: ""
  className: "gce"

command: ["bun"]
args: ["dist/index.js"]

resources:
  limits: { cpu: 800m, memory: 512Mi }
  requests: { cpu: 300m, memory: 256Mi }

terminationGrace: 30

config:
  API_GW_VALUE: "60000"
  PORT: 3000
