replicaCount: 1

image:
  tag: "{{ .Values.global.gitSha }}"
service:
  port: 8080

command: ["bun"]
args: ["dist/index.js"]

resources:
  limits: { cpu: 800m, memory: 512Mi }
  requests: { cpu: 300m, memory: 256Mi }

terminationGrace: 30

config:
  API_GW_VALUE: "60000"
