apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lib.fullname" . }}-stores
  labels: {{ include "lib.labels" . | nindent 4 }}
stringData:
{{- range $k, $v := .Values.global.backingStores }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
