name: Build & Deploy

on:
  push:
    branches: [develop, main] # ← вместо master
    paths: ["apps/**", "infra/**"]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  CLUSTER_NAME: helm-demo
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  get-affected-apps:
    uses: ./.github/workflows/get-affected-apps.yaml

  build-deploy:
    needs: get-affected-apps
    if: ${{ needs.get-affected-apps.outputs.has_affected_apps == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.affected_apps) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Install standalone Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - run: gcloud auth configure-docker $REGISTRY --quiet

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ matrix.app }}/${{ matrix.app }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{ is_default_branch }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Export project number
        run: |
          echo "PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID \
          --format='value(projectNumber)')" >> "$GITHUB_ENV"

      - id: gsm
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |
            COMMON_ENV:projects/${{ env.PROJECT_ID }}/secrets/COMMON_ENV/versions/latest

      - run: |
          echo "global:"           >  /tmp/secret-values.yaml
          echo "  backingStores:"  >> /tmp/secret-values.yaml
          printf '%b' "$RAW_COMMON"            \
          | sed '1s/^\xEF\xBB\xBF//'         \
          | jq -r 'to_entries[] | "    \(.key): \"\(.value)\""' \
          >> /tmp/secret-values.yaml

          cat /tmp/secret-values.yaml

      - uses: azure/setup-helm@v4

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$CLUSTER_NAME" \
            --region "$REGION" --project "$PROJECT_ID"

      - name: Helm upgrade / install
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.version }}
          REGISTRY: ${{ env.REGISTRY }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail

          APP="${{ matrix.app }}"
          CHART_DIR="infrastructure/services/${APP}"

          if [[ ! -f "${CHART_DIR}/Chart.yaml" ]]; then
            echo "::error ::Chart not found at ${CHART_DIR}"
            exit 1
          fi

          helm dependency build "${CHART_DIR}"

          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            ENV_FILE=prd
            NAMESPACE=prd
          else
            ENV_FILE=dev
            NAMESPACE=default
          fi

          echo "Deploying ${APP} to namespace ${NAMESPACE} using ${ENV_FILE}.yaml"

          helm upgrade "${APP}" "${CHART_DIR}" \
            -n "${NAMESPACE}" \
            -f infrastructure/globals/values-common.yaml \
            -f /tmp/secret-values.yaml \
            -f "${CHART_DIR}/values/${ENV_FILE}.yaml" \
            --set image.repository="${REGISTRY}/${PROJECT_ID}/${APP}/${APP}" \
            --set image.tag="${IMAGE_TAG}" \
            --set global.gitSha="${GITHUB_SHA}" \
            --install --atomic --wait --timeout 5m
