name: Build & Deploy

on:
  push:
    branches: [develop, main] # ← вместо master
    paths: ["apps/**", "infra/**"]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  CLUSTER_NAME: helm-demo
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  get-affected-apps:
    uses: ./.github/workflows/get-affected-apps.yaml

  build-deploy:
    needs: get-affected-apps
    if: ${{ needs.get-affected-apps.outputs.has_affected_apps == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.affected_apps) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - run: gcloud auth configure-docker $REGISTRY --quiet

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ matrix.app }}/${{ matrix.app }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{ is_default_branch }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Export project number
        run: |
          echo "PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID \
          --format='value(projectNumber)')" >> "$GITHUB_ENV"

      - id: gsm
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |
            COMMON_ENV:projects/${{ env.PROJECT_ID }}/secrets/COMMON_ENV/versions/latest

      - run: |
          echo "global:"           >  /tmp/secret-values.yaml
          echo "  backingStores:"  >> /tmp/secret-values.yaml
          printf '%b' "$RAW_COMMON"            \
          | sed '1s/^\xEF\xBB\xBF//'         \
          | jq -r 'to_entries[] | "    \(.key): \"\(.value)\""' \
          >> /tmp/secret-values.yaml

          cat /tmp/secret-values.yaml

            # ─── 1. ставим gke-gcloud-auth-plugin через apt ───
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      # ─── 2. получаем креды ───
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$CLUSTER_NAME" \
            --region "$REGION" --project "$PROJECT_ID"

      # ─── 3. Helm dependency build ───
      - name: Helm dependency build
        run: helm dependency build infrastructure/services/${{ matrix.app }}

      # ─── 4. Helm upgrade ───
      - name: Helm upgrade
        run: |
          ENV_FILE=$(test "${{ github.ref_name }}" = "main" && echo prd || echo dev)
          NAMESPACE=$(test "${{ github.ref_name }}" = "main" && echo prd || echo default)

          helm upgrade ${{ matrix.app }} infrastructure/services/${{ matrix.app }} \
            -n "$NAMESPACE" \
            -f infrastructure/globals/values-common.yaml \
            -f /tmp/secret-values.yaml \
            -f infrastructure/services/${{ matrix.app }}/values/$ENV_FILE.yaml \
            --set image.repository=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/\
            ${{ matrix.app }}/${{ matrix.app }} \
            --set image.tag=${{ steps.meta.outputs.version }} \
            --set global.gitSha=${{ github.sha }} \
            --install --atomic --wait --timeout 5m
